---
- name: Cron - copy to specify location
  copy: src=cron.sh dest=/usr/local/bin/cron.sh mode=0755 owner=answerable
  tags: deploy

- name: Cron - setup cronjob
  copy: src=drupal_cron dest=/etc/cron.d/drupal_cron mode=0644 owner=root
  become: yes
  become_method: sudo
  tags: deploy

- name: deploy private key for fetching git repository
  copy: src=id_rsa dest=/home/answerable/.ssh/id_rsa mode=0400 owner=answerable
  tags: deploy

- name: Create directory
  file: path={{ item }} state=directory mode=0755 owner=answerable
  become: yes
  become_method: sudo
  with_items:
    - /mnt/neticrm-7
    - /mnt/neticrm-6
  tags: deploy

- name: clone netiCRM
  git: repo=https://github.com/NETivism/neticrm.git dest=/mnt/neticrm-7/civicrm update=no clone=yes accept_hostkey=true
  tags: deploy
- git: repo=https://github.com/NETivism/neticrm.git dest=/mnt/neticrm-7/civicrm update=no clone=yes accept_hostkey=true
  tags: deploy
- shell: cd /mnt/neticrm-6/civicrm/neticrm && git checkout 6.x-develop && cd /mnt/neticrm-6/civicrm/drupal && git checkout 6.x-develop
  tags: deploy
- git: repo=git@git.netivism.com.tw:jimmy/neticrmp.git dest=/mnt/neticrm-7/neticrmp update=no clone=yes accept_hostkey=true
  tags: deploy
- git: repo=git@git.netivism.com.tw:jimmy/neticrmp.git dest=/mnt/neticrm-6/neticrmp update=no clone=yes accept_hostkey=true
  tags: deploy
- shell: cd /mnt/neticrm-6/neticrmp && git checkout develop
  tags: deploy

- name: upgrade netiCRM
  git: repo=https://github.com/NETivism/neticrm.git dest=/mnt/neticrm-7/civicrm update=yes clone=no accept_hostkey=true
  tags: upgrade
- git: repo=https://github.com/NETivism/neticrm.git dest=/mnt/neticrm-6/civicrm update=yes clone=no accept_hostkey=true force=yes
  tags: upgrade
- shell: cd /mnt/neticrm-6/civicrm/neticrm && git checkout 6.x-develop && git pull && cd /mnt/neticrm-6/civicrm/drupal && git checkout 6.x-develop && git pull
  tags: upgrade
- git: repo=git@git.netivism.com.tw:jimmy/neticrmp.git dest=/mnt/neticrm-7/neticrmp update=yes clone=no accept_hostkey=true
  tags: upgrade
- shell: cd /mnt/neticrm-6/neticrmp && git fetch --all && git reset --hard origin/develop
  tags: upgrade
