---
  - name: Copy drush execute file
    copy: src=drush dest=/usr/local/bin mode=0755 owner=root

  - name: Alias 'cd' to 'cd -P'
    lineinfile: dest=/etc/bash.bashrc line="alias cd='cd -P'"

  - name: remove exim4
    apt: name=exim4 state=absent
    ignore_errors: true 
  - apt: name=exim4-base state=absent
    ignore_errors: true 
  - apt: name=exim4-config state=absent
    ignore_errors: true 
  - apt: name=exim4-daemon-light state=absent
    ignore_errors: true 
