---
# Deploy a site.
- name: Deploy a site
  shell: /etc/ansible/docker-sh/docker-start.sh -d {{ DOMAIN }} -w {{ PORT_WWW }} -m {{ PORT_DB }} -r {{ REPOS }} -p {{ PASSWD }}
  sudo: yes
  tags:
    - start

- name: Restart a site
  shell: /etc/ansible/docker-sh/docker-start.sh -d {{ DOMAIN }}
  sudo: yes
  tags:
    - restart
