---
# Clone docker-sh repository and deploy a site.
- name: Fetch docker-sh repository
  # http://docs.ansible.com/git_module.html
  git: repo=https://github.com/NETivism/docker-sh.git dest=/home/gloomcheng/docker-sh accept_hostkey=yes
  sudo_user: root
  tags:
    - start

- name: Deploy a site
  shell: /home/gloomcheng/docker-sh/docker-start.sh -d "{{ DOMAIN }}" -w "{{ PORT_WWW }}" -m "{{ PORT_DB }}" -r "{{ REPOS }}" -p "{{ PASSWD }}"
  sudo_user: root
  tags:
    - start

- name: Restart a site
  shell: /home/gloomcheng/docker-sh/docker-start.sh -d "{{ DOMAIN }}"
  sudo_user: root
  tags:
    - restart
