---
# Create a docker container and deploy a site.
- name: Checkout docker-sh repo from github
  git: repo=https://github.com/NETivism/docker-sh.git dest=/etc/ansible/docker-sh accept_hostkey=yes
  tags:
    - start

- name: Deploy a site
  shell: ./docker-start.sh -d {{ domain }} -w {{ port_www }} -m {{ port_db }} -r {{ repos }} -v {{ MOUNT }} -u {{ DBNAME }} -p {{ passwd }} chdir=/etc/ansible/docker-sh
  tags:`
    - start

- name: Restart a site
  shell: ./docker-start.sh -d {{ domain }} chdir=/etc/ansible/docker-sh
  tags:
    - restart
