---
  - name: Nginx should be started
    service: name=nginx state=started
    tags:
      - start

  - name: Copy override config file
    file: path=/etc/nginx/include state=directory mode=0755 owner=answerable
    tags:
      - start
      - reload

# due to bug https://github.com/ansible/ansible-modules-core/issues/1162, change to copy
#  - synchronize: src=/etc/ansible/ansible-docker/playbooks/roles/nginx/files/ dest=/etc/nginx/include archive=no delete=yes recursive=yes
#    tags:
#      - start

  - copy: src={{ item }} dest=/etc/nginx/include/ owner=root mode=644
    with_fileglob:
      - ./*
    tags:
      - start
      - reload 

  - name: Add Nginx vhost configuration file
    # http://docs.ansible.com/template_module.html
    template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{ domain }}
    tags:
      - start

  - name: Link Nginx vhost configuration file in site-enabled
    action: file src=/etc/nginx/sites-available/{{ domain }} dest=/etc/nginx/sites-enabled/{{ domain }} state=link
    notify:
      - validate nginx
    tags:
      - start

  #- name: Add site alias into Nginx vhost configuration file
  #  # http://docs.ansible.com/lineinfile_module.html
  #  lineinfile: 
  #    dest: /etc/nginx/sites-available/{{ domain }} 
  #    regexp: '^(.*)server_name {{ domain }}(.*)$'
  #    line: '\1server_name {{ domain }} {{ alias }}\2'
  #    state: present
  #    backrefs: yes
  #  tags:
  #    - alias

  #- name: Remove site alias from Nginx vhost configuration file
  #  lineinfile:
  #    dest: /etc/nginx/sites-available/{{ domain }}
  #    regexp: '^(.*) {{ alias }}(.*)$'
  #    line: '\1\2'
  #    state: present
  #    backrefs: yes
  #  tags:
  #    - unalias

  - name: Reload nginx
    service: name=nginx state=reloaded
    tags:
      - start
      - reload
  #    - alias
  #    - unalias
