---
  - name: Nginx should be started
    service: name=nginx state=started
    sudo: yes
    tags:
      - start

  - name: Copy desired nginx config file
    copy: src={{ type }}.conf dest=/etc/nginx/{{ type }}.conf owner=root group=root mode=0644
    sudo: yes
    tags:
      - start

  - name: Add Nginx vhost configuration file
    # http://docs.ansible.com/template_module.html
    template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{ domain }}
    sudo: yes
    tags:
      - start

  - name: Link Nginx vhost configuration file in site-enabled
    action: file src=/etc/nginx/sites-available/{{ domain }} dest=/etc/nginx/sites-enabled/{{ domain }} state=link
    sudo: yes
    notify:
      - validate nginx
    tags:
      - start

  - name: Add Alias into Nginx vhost configuration file
    # http://docs.ansible.com/replace_module.html
    #replace:
    #  dest=/etc/nginx/sites-available/{{ domain }}
    #  regexp='{{ domain }}'
    #  replace='{{ domain }} {{ alias }}'
    #tags:
    #  - alias

  - name: Reload nginx
    sudo: yes
    service: name=nginx state=reloaded
    tags:
      - start
      - reload
