---
  - name: Add Nginx vhost configuration file
    # http://docs.ansible.com/template_module.html
    template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{ domain }}
    sudo: yes
    tags:
      - start

  - name: Link Nginx vhost configuration file in site-enabled
    action: file src=/etc/nginx/sites-available/{{ domain }} dest=/etc/nginx/sites-enabled/{{ domain }} state=link
    sudo: yes
    notify:
      - Restart Nginx
    tags:
      - start
