---
- name: Check if user exists
  shell: /usr/bin/getent passwd {{ item }} > /dev/null && echo "" || echo {{ item }}
  with_items: "{{ user_ssh }} + {{ user_sftp }}"
  register: tmpvar
  tags:
    - useradd

- shell: echo {{ item.stdout }}
  with_items: "{{ tmpvar.results }}"
  register: user_exists
  when: item.stdout != ""
  tags:
    - useradd

# Add a user with a bash shell, appending the group 'www-data' and 'developer' to the user's groups
- name: Create ssh group
  group: name=userssh state=present
  tags:
    - useradd

- name: Create sftp group
  group: name=usersftp state=present
  tags:
    - useradd

- name: Random passwords
  shell: openssl rand -base64 20
  with_items: "{{ user_exists.results }}"
  when: item.changed
  register: user_passwd
  tags:
    - useradd

- name: Encryped passwords
  shell: mkpasswd --method=SHA-512 {{ item.stdout }}
  with_items: "{{ user_passwd.results }}"
  when: item.stdout is defined
  register: encryped_passwd
  tags:
    - useradd

- name: Add users
  user: name={{ item.0.stdout }} state=present group=userssh comment=ansible password={{ item.1.stdout }} shell=/bin/bash
  with_together: 
    - "{{ user_exists.results }}"
    - "{{ encryped_passwd.results }}"
  when: item.0.stdout is defined
  tags:
    - useradd

- name: Limit SFTP user
  user: name={{ item }} state=present group=usersftp groups=usersftp comment=ansible shell=/bin/sh
  with_items: "{{ user_sftp }}"
  tags:
    - useradd

- name: Display generated password
  debug: 
    msg: |
      {% set comma = joiner(",") %}
      {% for item in user_exists.results -%}
        {% if item.stdout is defined %}{% set idx = loop.index - 1 %} {{ comma() }} {{ item.stdout }}=>{{ user_passwd.results[idx].stdout }}{% endif %}
      {%- endfor %}
  tags:
    - useradd

# change password
- name: Encryped password from variable
  shell: mkpasswd --method=SHA-512 {{ pass }}
  register: password
  tags:
    - passwd
- name: Change user password for {{ username }}
  user: name={{ user }} state=present password={{ password.stdout }}
  tags:
    - passwd
