---
# file: docker.yml
- hosts: '{{ target }}'
  remote_user: answerable
  sudo: yes
  roles:
    - docker
    - nginx

- hosts: localhost
  connection: local
  vars_files:
    - '/etc/ansible/target/{{ target }}/hostname'
  sudo: yes
  roles:
    - dns
