---
# Initial linode image and create remote user account for ansible.
- hosts: "{{ target }}"
  remote_user: root
  sudo: no
  roles:
    - init

- hosts: localhost
  connection: local
  sudo: yes
  tasks:
    - name: Create target directory.
      file: path=/etc/ansible/target/{{ target }} state=directory
    - name: Create hostname directory.
      template: src=hostname.j2 dest=/etc/ansible/target/{{ target }}
    - name: Create redirect file.
      template: src=redirect.j2 dest=/etc/ansible/target/{{ target }}
    - name: Create user file.
      template: src=user.j2 dest=/etc/ansible/target/{{ target }}
    - name: Create vmail file.
      template: src=vmail.j2 dest=/etc/ansible/target/{{ target }}
