---
# file: rolling_upgrade.yml
- hosts: "{{ target }}"
  remote_user: answerable
  sudo: yes
  roles:
    - common
    - timezone
    - ntp
  vars:
    timezone: Asia/Taipei
    ntp_timezone: Asia/Taipei
  tasks:
    - include: roles/common/tasks/update_docker.yml
      when: update_docker
